### ISSUE TITLE
Use pnpm instead of yarn

### ISSUE THREAD

**Issue by darrylyeo** [scaffold-eth/scaffold-eth-2#290]
[`pnpm`](https://pnpm.io/) supports monorepos like `yarn` and comes with benefits like [faster npm package install times](https://pnpm.io/benchmarks#lots-of-files) and a [content-addressable storage that saves disk space](https://pnpm.io/motivation). It'll be a huge time-saver for devs who work with lots of codebases and/or Scaffold-Eth-2 forks that share lots of dependencies.

**Comment by sverps** [comment]
Hey @darrylyeo, thanks for the suggestion. 

I don't have a strong preference for either, but I think it's probably not worth it to switch now. The difference with yarn v2 is minimal, and users are now already familiar with that since the previous `scaffold-eth` also used it.

Maybe it would be nice to give some package manager options in the npx create tool we're thinking to implement (#251), but this will probably remain rather low prio.

**Comment by schmidsi** [comment]
+1 for package manager options, that being said, I think this is low priority.

**Comment by schmidsi** [comment]
Throwing this in here as it's the news of the weekend in the JavaScript bubble: [Bun](https://bun.sh) is stable: https://twitter.com/bunjavascript/status/1700148056706949627

**Comment by roninjin10** [comment]
Bun is super bleeding edge and you get the odd segfault with no helpful error message from time to time still. But if you use only the package manager to install node modules and otherwise keep using node as the runtime it's a pretty solid choice. Anything is better than yarn

**Comment by carletex** [comment]
Yarn has been working great for us since SE-1.

We have a PR for pnpm https://github.com/scaffold-eth/scaffold-eth-2/pull/444 almost ready to go, and we are thinking about it.

The only reason we decided to explore it was because of the individual lockfile per package (which is great for monorepos and avoids extra configuration on Vercel/etc). It will also help our CLI.

The release of Bun 1.0 also made me think, thanks @schmidsi for bringing it up! But It might be to early to consider... and also not sure if they support individual lockfiles! We'll keep an eye on it tho.

**Comment by carletex** [comment]
Closing this for now. More info: https://github.com/scaffold-eth/scaffold-eth-2/pull/444
