### ISSUE TITLE
Notification error not user friendly

### ISSUE THREAD

**Issue by KcPele** [scaffold-eth/scaffold-eth-2#301]
The notification error that is been displayed is not user friendly
It should be formatted properly and only the reason for the error should be seen
![Screenshot from 2023-04-10 09-56-22](https://user-images.githubusercontent.com/64108987/230869792-38422f14-268a-4717-a1e8-841f3bd75c7f.png)

**Comment by kevinjoshi46b** [comment]
I had raised similar concerns in #286 
@sverps maybe we can discuss the pros/cons here?

**Comment by KcPele** [comment]
This is different. I am not talking about the theme. it is about the error itself. The one in #286 is about the theme

**Comment by kevinjoshi46b** [comment]
Please do correct me if I am wrong but what you mean is to have a message shown as "Campaign deadline has not passed yet" / " Something went wrong" instead of this huge error json being presented in the notification right? If so then that is what I was talking about in this comment: https://github.com/scaffold-eth/se-2/issues/286#issuecomment-1499866944

**Comment by KcPele** [comment]
If u check in #286 one of the comment is that another issue should be open that handles the way the error is been displayed. so this is the issue, not to worry its fine, i will close the issue after creating a pr for it

**Comment by technophile-04** [comment]
Tysm for the issue 🙌

Actually parsing errors nicely with ethers v5 is really hard, check out the original comment -> https://github.com/scaffold-eth/se-2/pull/36#discussion_r1018310035

I think with ethers v6 this is solved somewhat checkout -> https://github.com/ethers-io/ethers.js/issues/2475#issuecomment-1428671151

But I think we may go on the path of [VIEM](https://www.viem.sh) instead of upgrading to v6(not clear yet) since WAGMI v1.0 is migrating from ethers to [VIEM](https://www.viem.sh). 

We already had this discussion about migration at #229, so marking this as `waiting` since currently migration is not top priority yet.

**Comment by jxom** [comment]
this is what ethers v6 looks like right now: https://twitter.com/jakemoxey/status/1633240447761121281?s=20

**Comment by KcPele** [comment]
I have been able to write a function that returns a better error message
![Screenshot from 2023-04-13 11-05-15](https://user-images.githubusercontent.com/64108987/231727171-341df6ea-271a-4d8b-bfc5-983117a9f002.png)
![Screenshot from 2023-04-13 11-06-20](https://user-images.githubusercontent.com/64108987/231727273-592269dd-ab14-4ec5-94a0-e26fa4309121.png)

**Comment by kevinjoshi46b** [comment]
Yes this is what I was imagining too.
Console log the complete json and display only important bits in the notification.

**Comment by sverps** [comment]
Hey @KcPele , thanks for having a crack at this, I've checked the PR and put some comments, but the general feeling I have is that the best approach would probably be to just improve the parsing that is done by `getParsedEthersError`, rather than re-create some new function.

**Comment by technophile-04** [comment]
Thanks guys 🙌, closing this in favour of https://github.com/scaffold-eth/scaffold-eth-2/pull/352#issuecomment-1613678571
