### ISSUE TITLE
bug: Dark mode colors are the same as base colors

### ISSUE THREAD

**Issue by ByteAtATime** [scaffold-eth/scaffold-eth-2#355]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Current Behavior

The base colors in the dark DaisyUI theme are the same as `primary` and `secondary`. Here is the config for reference:

```
primary: "#212638",
secondary: "#2A3655",

"base-200": "#2A3655",
"base-300": "#212638",
```

Notably, `primary` = `base-300` and `secondary` = `base-200`.

### Expected Behavior

I believe there should be a distinct difference, such as in the official DaisyUI dark theme, where there are dark base colors and vibrant, saturated primary and secondary colors.

**Comment by sverps** [comment]
Can you provide some screenshots where this poses an issue? Not sure I fully understand.

**Comment by ByteAtATime** [comment]
Not really an issue, but I feel like this defeats the purpose of having a background. For example, on the "Cast Vote" page of my [simple voting app](https://buidlguidl.com/build/zrlotAYlNAy8pbekQU8y), you can see that the "Vote" button doesn't seem to have a background on the dark theme:
![B153C433-45EA-46F2-AB4A-1AA90B29ABDB](https://github.com/scaffold-eth/scaffold-eth-2/assets/104588511/1547e9ad-f0cd-4863-a86a-e2e0082aa0b8)

This doesn't happen on the light theme, however:
![45906394-557E-4EB5-9B5B-3494C23180F1](https://github.com/scaffold-eth/scaffold-eth-2/assets/104588511/d9fd57d4-0e80-451b-a404-d6ad4cc02b44)

**Comment by sverps** [comment]
Ah, I understand :+1: 
In the main repo, it doesn't cause issues since we never use the button outside of a containing card-like element (and it's not really intended).

So you can either modify your design a bit to follow this pattern, or you can tweak the configured colors for your project to give it a more personalized look-and-feel.

Hope that you can resolve this for your project this way :rocket:
