### ISSUE TITLE
yarn deploy not working

### ISSUE THREAD

**Issue by WingsDevelopment** [scaffold-eth/scaffold-eth-2#367]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Current Behavior

yarn deploy
result in: 
yarn run v1.22.1
$ yarn workspace @se-2/hardhat deploy
warning package.json: No license field
$ hardhat deploy --export-all ./temp/hardhat_contracts.json "$@" && hardhat run scripts/generateTsAbis.ts
Error HH308: Unrecognized positional argument $@

For more info go to https://hardhat.org/HH308 or run Hardhat with --show-stack-traces
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: C:\Program Files\nodejs\node.exe
Arguments: C:\Users\bansc\Documents\GitHub\scaffold-test\.yarn\releases\yarn-1.22.1.cjs deploy
Directory: C:\Users\bansc\Documents\GitHub\scaffold-test\packages\hardhat
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Steps To Reproduce

Download project from github, run 
yarn install
yarn deploy

### Anything else?

I am on windows..
Yarn version: yarn run v1.22.1
Node version:
v18.16.0

what am i missing ?

**Comment by sverps** [comment]
Hey, thanks for pointing this out and taking the time to create an issue for it.

I'm afraid this is an issue related to Windows file system and terminal syntax being too different from Unix systems that are used to develop and test scaffold-eth-2.

A couple of options you have:
- Remove the `\"$@\"` bit from the `deploy` script in `packages/hardhat/package.json` since this seems to be causing issues on windows. (Note that with this removed, some functionality will no longer work, such as `yarn deploy --reset` or anything else requiring passing params to the deploy script.
- Install [Windows Subsystem for Linux](https://learn.microsoft.com/en-us/windows/wsl/install) to create a Linux environment on windows (works quite well for a lot of things, haven't tested it on scaffold-eth-2 personally, but I think it should work)
- Or go for a dual boot or full linux install

(Leaving this issue open, since ideally, at some point, we should try and figure out how to reliably get scaffold-eth-2 working on Windows)

**Comment by carletex** [comment]
Not sure why, but this doesn't happen in all Windows systems. Maybe because people use a different shell or WSL?

@sverps Your suggestion here https://github.com/scaffold-eth/scaffold-eth-2/pull/354#issuecomment-1572079921 will fix this (since we won't need the  \"$@\" && anymore). Should we create a draft PR and see how it feels?

**Comment by sverps** [comment]
Yeah sounds good, I'll create a draft PR :+1:

**Comment by KcPele** [comment]
I will also try to reproduce the error
