### ISSUE TITLE
bug: Argument of type '{ contractName: string; functionName: string; }' is not assignable to parameter of type 'never'.

### ISSUE THREAD

**Issue by samyogdhital** [scaffold-eth/scaffold-eth-2#371]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Current Behavior

**Description**:

I encountered a type error when attempting to build the Next.js frontend package using `yarn build`. The error message is as follows:

![image](https://github.com/scaffold-eth/scaffold-eth-2/assets/91406792/c480069e-5c9b-4de7-a29b-7ce38c63a166)

**Steps to reproduce**:

1. Clone the repository and navigate to the project directory.
2. Install the required dependencies using `yarn install`.
3. Run `yarn build` to build the Next.js frontend package.

**Expected behavior**:

The frontend package should build successfully without any type errors.

**Actual behavior**:

The build process fails with the following error message:

```
Argument of type '{ contractName: string; functionName: string; }' is not assignable to parameter of type 'never'.
```

**Environment**:

- OS: Windows 11
- Node.js version: 18.25.0
- Yarn version: 3.2.3
- Next.js version: 13.1.6

**Comment by sverps** [comment]
I tried reproducing this, but here it builds fine. Not sure what's going on on your end. Do you have a repo with the project in this specific state with this issue?

**Comment by samyogdhital** [comment]
@sverps Thanks for reaching out. Here is the forked version https://github.com/samyogdhital/scaffold-deploy. Not sure what happened in my end.

**Comment by sverps** [comment]
Hey @samyogdhital , the issue is that your `scaffold.config.ts` is targetting `chains.hardhat`, but the `deployedContracts.ts` definitions only have the deployment info for sepolia. To unblock, you can spin up a hardhat node (`yarn chain`) and then deploy to it (`yarn deploy`) so that it generates the missing things.

Meanwhile, I'm investigating if we can improve the types to more gracefully handle this edge-case (since usually when building the next package, you'd do that targeting a network where it's for sure deployed).

**Comment by samyogdhital** [comment]
Thanks @sverps!🥂 since I am tryna deploy to sepolia so changed to `targetNetwork: chains.sepolia`.
