### ISSUE TITLE
bug: Switching to a different target network in scaffold.config produces a stream of unrelated errors

### ISSUE THREAD

**Issue by alvatar** [scaffold-eth/scaffold-eth-2#378]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Current Behavior

Just changing the network from chains.hardhat to chains.arbitrum or other in scaffold.config.ts produces this.

This is the error I get.

```
Type error: Implicit conversion of a 'symbol' to a 'string' will fail at runtime. Consider wrapping this expression in 'String(...)'.

  63 |     return (
  64 |       <p className="text-3xl mt-14">
> 65 |         {`No contract found by the name of "${contractName}" on chain "${configuredNetwork.name}"!`}
     |                                               ^
  66 |       </p>
  67 |     );
  68 |   }
```

Seems simple enough so I do the conversion. It asks again at another place, but then I reach at:

```
./hooks/scaffold-eth/useDeployedContractInfo.ts:14:5
Type error: Type 'symbol' cannot be used as an index type.

  12 |   const isMounted = useIsMounted();
  13 |   const deployedContract = contracts?.[scaffoldConfig.targetNetwork.id]?.[0]?.contracts?.[
> 14 |     contractName as ContractName
     |     ^
  15 |   ] as Contract<TContractName>;
  16 |   const [status, setStatus] = useState<ContractCodeStatus>(ContractCodeStatus.LOADING);
  17 |   const provider = useProvider({ chainId: scaffoldConfig.targetNetwork.id });
```

This one I don't know how to fix.

### Expected Behavior

In the main repo this doesn't happen, but I have no clues on what could be the cause, as I'm not touching any of this code or calling it directly. I'm just using the Read and Write calls regularly.

### Steps To Reproduce

I don't know how to reproduce, as this seems quite unrelated to my code. If it's really necessary I can try again to make a separate repo, but it took me hours yesterday to figure out how to trigger the other error, so perhaps you have an idea before I spend hours on this again. Thanks!

**Comment by sverps** [comment]
It's probably because after changing the config, you forgot to deploy the contract to this network, and your `contract.ts` file doesn't have the proper types for it.

There is a PR open that would resolve these type errors #372, then you would be able to run the project, and you'd likely get some feedback in the frontend that the selected contract isn't deployed.

**Comment by alvatar** [comment]
Thanks for your reponse.
So I have to deploy like this:

```
yarn deploy --network arbitrum
```

before I can build changing to that network?
The most confusing part is that this doesn't seem to be necessary if I do it on the HEAD of this repo

**Comment by technophile-04** [comment]
> The most confusing part is that this doesn't seem to be necessary if I do it on the HEAD of this repo

Actually in HEAD of the repo you checkout [`deployedContract.ts`](https://github.com/scaffold-eth/scaffold-eth-2/blob/main/packages/nextjs/generated/deployedContracts.ts) it has `deployedContract = null` and we had handled the case to no show errors when `deployedContract = null` and be `targetNetwork` set to any network thats why you are not getting any error 

But once you deploy your contract to any chain `deployedContract = {...}` which is no more `null` now if you switch the `targetNetwork` to another chain which is not present as key in `deployedContract = {...}`  it throws an error 

This issue was handled in #372 and you wont face error for the above case 

@alvatar could you just pull the changes or copy-paste the changes done in #372 , hopefully, it will solve the issue 

please close the issue if it solves the problem 🙌

**Comment by alvatar** [comment]
oh, yes, thanks a lot!! It does solve the problem.

A question about this: is this fix allowing me to deploy the frontend even if I don't have the contracts deployed, or I will have to re-deploy the frontend?

Also, if you don't mind me asking, because I'm trying to figure out how to do this and I can't find a good way. What's a good way to handle external contracts that you need to read/write on the frontend? I'm using directly the wagmi functions, but specifically for their addresses, I wonder is there is a good way to configure those based on the target network? I was thinking, perhaps the networks.ts file, in NETWORKS_EXTRA_DATA, and there getting it from an environment variable? Thanks a lot!

**Comment by sverps** [comment]
> A question about this: is this fix allowing me to deploy the frontend even if I don't have the contracts deployed, or I will have to re-deploy the frontend?

You'll have to re-deploy the frontend (since it dynamically resolves the contract address based on what is generated in `deployedContract.ts`).

In local development, however, next will automatically detect file changes to `deployedContract.ts` and update the frontend to match.

> What's a good way to handle external contracts that you need to read/write on the frontend?

Using wagmi is probably the best approach for external contracts. If you want it to "automatically" work when changing target network, you could create a mapping object that maps network to external contract address. Other approaches are definitely possible, depends a bit on your preferences.

**Comment by sverps** [comment]
Closing this issue now that it's resolved, but feel free to ask any other questions you might have. :)

**Comment by alvatar** [comment]
Thanks!

Yes, I would love to ask a question @sverps if you don't mind :)
I'm deploying to Digital Ocean (not using Vercel), and for that I use this script in package.json:

```
         "serve-digitalocean": "yarn workspace @se-2/nextjs next start -H 0.0.0.0 -p ${PORT:-8080}",
```

The result compiles and serves nicely, but nothing works (no contract reads/writes work, no data shows) and I can't see any console error.

Is there a way to run the server in "dev mode" to get more info in the console?
Also, am I missing any step? The README only explains how to proceed with Vercel, but perhaps I'm missing some details.
I've deployed the contracts to Arbitrum Goerli successfully, Metamask connects to it, and I've compiled and deployed with the scaffold.config.ts corresponding network option.

**Comment by sverps** [comment]
Make sure you `deployedContract.ts` is also committed to your repo.

Can you share the rest of your build steps? How is your build output deployed to digital ocean?

Is it a VPS? Can you SSH into it and check if your `deployedContract.ts` on the VPS is complete?

**Comment by alvatar** [comment]
It was my bad. Nothing to do with scaffold. Thanks anyway!
