### ISSUE TITLE
bug: <title> useScaffoldContract not exposing contract functions.

### ISSUE THREAD

**Issue by 0xChijoke** [scaffold-eth/scaffold-eth-2#459]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Current Behavior

I tried to use the contract instance in my project using useScaffoldContract, but it came back undefined for a function that exists in the abi.

I assumed its an issue with the project but I have come across another builder with the same issue.

![image](https://github.com/scaffold-eth/scaffold-eth-2/assets/53488449/ef89ab77-30d0-4467-872d-c1595ec74a9e)

### Expected Behavior

Should be able to call contract functions from a useScaffoldContract instance.

### Steps To Reproduce

Can be reproduced by creating a contract instance with the useScaffoldContract hook.

  const { data: noob } = useScaffoldContract({ contractName: "Noob" });
  console.log("noob: ", noob);
  console.log("Noob supply: ", noob?.totalSupply)

### Anything else?

![image](https://github.com/scaffold-eth/scaffold-eth-2/assets/53488449/ef89ab77-30d0-4467-872d-c1595ec74a9e)

![image](https://github.com/scaffold-eth/scaffold-eth-2/assets/53488449/630981b0-af02-4679-8f95-ae817848d3c3)

**Comment by technophile-04** [comment]
Tysm @0xChijoke for the issue 🙌 

Actually we forgot to update README after migration there is some api change because using viem : 

To `read` you need to do : 
 ```
 await yourContract?.read.greeting();
 ```
 
 You can check updated readme at this commit -> https://github.com/scaffold-eth/scaffold-eth-2/pull/460/commits/6a8e45deb4c43a617099ae6873674cf64c6b4401
 
 
 But yeah currently there are missing auto completions for useScaffoldContract which is tackled in this #460 🙌
 
 Thanks again 🙌

**Comment by 0xChijoke** [comment]
@technophile-04  Awesome 👏
