### ISSUE TITLE
bug: Block explorer skips transactions

### ISSUE THREAD

**Issue by portdeveloper** [scaffold-eth/scaffold-eth-2#528]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Current Behavior

Currently block explorer skips transactions if they are coming too fast and it also is pretty slow.

https://github.com/scaffold-eth/scaffold-eth-2/assets/108868128/54a64bc6-95a9-49a7-9ecf-b740316f0e0a

### Expected Behavior

By upgrading to a websocket transfer from http, we get instant feedback in the ui, in addition to not skipping any transactions.

https://github.com/scaffold-eth/scaffold-eth-2/assets/108868128/be5b70c4-e67e-4e95-8777-a77b30c6088b

**Comment by luksgrin** [comment]
Hello! I just noticed you were also struggling with the blockexplorer. [This issue](https://github.com/scaffold-eth/scaffold-eth-2/issues/524) is _kind of_ related... check it out!

It would be a universal benefit if the [`useFetchBlocks`](https://github.com/technophile-04/foundry-goerli-fork-524/blob/foundry-goerli-fork/packages/nextjs/hooks/scaffold-eth/useFetchBlocks.ts) hook gets optimized 😍 .

Anyways, these are my two cents 😅

**Comment by portdeveloper** [comment]
> Hello! I just noticed you were also struggling with the blockexplorer. [This issue](https://github.com/scaffold-eth/scaffold-eth-2/issues/524) is _kind of_ related... check it out!
> 
> It would be a universal benefit if the [`useFetchBlocks`](https://github.com/technophile-04/foundry-goerli-fork-524/blob/foundry-goerli-fork/packages/nextjs/hooks/scaffold-eth/useFetchBlocks.ts) hook gets optimized 😍 .
> 
> Anyways, these are my two cents 😅

Thanks for letting me know of this. I am also thinking about not having the transactionReceipts as a seperate state variable. 
Since this PR only concerns the hardhat version I think we should merge it then we can check if it works with anvil, or we can directly optimize the block explorer for anvil use, since anvil is used more than hardhat these days.

**Comment by technophile-04** [comment]
> Since this PR only concerns the hardhat version I think we should merge it then we can check if it works with anvil, or we can directly optimize the block explorer for anvil use, since anvil is used more than hardhat these days.

Yup, we can tackle it one by one 🙌

Btw the issue mentioned in #524 is no more `hardhat` vs `anvil` because we found [this solution](https://github.com/scaffold-eth/scaffold-eth-2/issues/524#issuecomment-1714558947)  but now it's more of optimizing / making block explorer work when people fork the chain. 

Because when you fork the chain in current se-2 hardhat `main` branch we get same as mentioned [in this comment video and note](https://github.com/scaffold-eth/scaffold-eth-2/issues/524#issuecomment-1711082748) 

> https://github.com/scaffold-eth/scaffold-eth-2/assets/80153681/fb0774b7-9427-4282-b76b-19759be4e24c

> NOTE: After loading is complete, there is slight blank screen with no data but its internally fetching all transactionReceipt so you have to wait a bit to see all the data (This needs to be handle)


--- 

Nevertheless, let's get #529 nicely working when using the local chain (without thinking much of forking chain use case but also having it in the back of mind)

After that we can work on reducing no. of RPC call each page requires like we have `BLOCKS_PER_PAGE = 20` but for some reason we are making more than 20 `eth_getBlockByIndex` calls (noticed while forking chain don't know if its true when using local chain)

But yeah again let's not worry  too much about fork chain, if its a quick fix lets push the changes in #529 or we can handle it in a different PR eg: "Optimize  blockexplorer when forking chain"

Thanks Port !!
