### ISSUE TITLE
BurnerConnector does not emit standard events

### ISSUE THREAD

**Issue by norswap** [scaffold-eth/scaffold-eth-2#588]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Current Behavior

Connectors in wagmi are expected to emit [these events](https://github.com/wagmi-dev/wagmi/blob/main/packages/connectors/src/base.ts#L13-L19).

This can be seen in Wagmi's own connector implementation, e.g. [here in MockConnector](https://github.com/wagmi-dev/wagmi/blob/8128c29dd38f2b079fc0ff427ff024dd141f2af9/packages/connectors/src/mock/connector.ts#L135-L145).

If you do not emit these events, then some of Wagmi features won't work, for instance the `watchAccount` action that fires whenever the connected account changes won't fire its callback.

(I stumbled on this issue while looking for a burner wallet Wagmi connector, and ran into this exact problem.)

**Comment by technophile-04** [comment]
> For instance the `watchAccount` action that fires whenever the connected account changes won't fire its callback.

I just tried using `watchAccount`  and it seem to be working : 

https://github.com/scaffold-eth/scaffold-eth-2/assets/80153681/d0d8572b-852e-4965-9eb6-21974a1fa014

My guess is since we are using `@ethersproject/providers` =>  `StaticJsonRpcProvider` it's handling it but will try to dig in, also while testing it seems to work nicely  

Would really appreciate it if you could pass an SE-2 MRR where it's not working properly, but thanks @norswap for raising it  🙌

**Comment by norswap** [comment]
Ah, that would make sense. I'll admit I only recently discovered the provider standard, but that would logical that it fills that role since it has notification method for just that pupose. I'm not returning any provider from my connector, which causes wagmi to use a default one.

I have no idea what a SE-2 MRR!

Didn't test anything, was just my observation that the events were not emitted and emitting them fixed the issues I had on my side. If it works, that's great, I'll just close this issue :)
